parent=keycloak.v2
import=common/keycloak

styles=css/styles.css css/analitrics.css
stylesCommon=vendor/patternfly-v5/patternfly.min.css vendor/patternfly-v5/patternfly-addons.css

darkMode=true

kcLogoIdP-facebook=
kcLogoIdP-google=
kcLogoIdP-github=
kcLogoIdP-linkedin=
kcLogoIdP-microsoft=
