services:
  phoenix:
    image: arizephoenix/phoenix@sha256:5ae3c414e8ee7ee47caa022edf8e94bdef7a90634a4e914a99dbe9d1f70790b8
    container_name: analitrics-observability-phoenix
    restart: unless-stopped
    environment:
      PHOENIX_HOST: 0.0.0.0
      PHOENIX_PORT: 6006
      PHOENIX_GRPC_PORT: 4317
      PHOENIX_WORKING_DIR: /mnt/data
      PHOENIX_ALLOW_EXTERNAL_RESOURCES: "false"
    ports:
      - "127.0.0.1:6006:6006"
      - "127.0.0.1:4317:4317"
    volumes:
      - type: bind
        source: /var/analitrics/observability/phoenix
        target: /mnt/data
    networks:
      network-analitrics:
        aliases:
          - phoenix

networks:
  network-analitrics:
    external: true
